### ISSUE TITLE
Allow editing the values of exiting storage entries

### ISSUE THREAD

**Issue by SebastianZ** [NickBelhomme/firestorageplus#2]
There should be a possibility to edit the entries of the storages.
This could be done via a separate editor like editing cookies inside the _Cookies_ panel. Though a better UI would be to have an inline editor like suggested for the _Cookies_ panel in [issue 5542](http://code.google.com/p/fbug/issues/detail?id=5542).

Sebastian

**Comment by NickBelhomme** [comment]
released in version 1.2
