### ISSUE TITLE
Allow adding new storage entries

### ISSUE THREAD

**Issue by SebastianZ** [NickBelhomme/firestorageplus#3]
There should be a possibility to add new entries to the storages.
As described in [issue 2](https://github.com/NickBelhomme/firestorageplus/issues/2) there could be a separate editor dialog for this like inside the _Cookies_ panel. Or there could be an inline editor for that, which integrates nicer into the UI.

Sebastian

**Comment by NickBelhomme** [comment]
released in version 1.2
