### ISSUE TITLE
Allow sorting by columns

### ISSUE THREAD

**Issue by SebastianZ** [NickBelhomme/firestorageplus#5]
The user should be able to sort the _Name_ and _Value_ column alphabetically by clicking their headers like it's possible e.g. inside the _Net_ and _Cookies_ panel.

Sebastian

**Comment by NickBelhomme** [comment]
This has been implemented in the last commit.
Will be included in the next official addon release.

Issue remains open until deployed in production (gallery).

**Comment by SebastianZ** [comment]
Good to hear. Thanks for the quick fix!

Sebastian
