### ISSUE TITLE
Allow changing width of the columns

### ISSUE THREAD

**Issue by jakub-g** [NickBelhomme/firestorageplus#8]
The goal of this issue is either to:
- allow changing width of the columns,
- or alter the way the width is calculated.

Currently the columns have automatic width. It's not so bad by default, but:
- when you increase the font size in Firebug using `Ctrl`+`+`,
- or just have a narrow screen / browser window etc.

then the first column takes the majority of the space and the others are not visible at all or very narrow, with overflowing text.

**Comment by NickBelhomme** [comment]
Thanks for the issue report. This will be picked up in the next release.

Thanks for using FireStorage Plus!
Follow us on twitter: https://twitter.com/FireStoragePlus
Become a fan on Facebook: https://www.facebook.com/FireStoragePlus

**Comment by NickBelhomme** [comment]
Implemented and available in release v1.5

**Comment by jakub-g** [comment]
That was fast! Seems to be working fine. Thanks!
